using ProjectHub.Domain.Common;
using ProjectHub.Domain.Enums;
using ProjectHub.Domain.Events;
using ProjectHub.Domain.Exceptions;
using ProjectHub.Domain.Primitives;
using ProjectHub.Domain.ValueObjects;

namespace ProjectHub.Domain.Entities;

public sealed class User : AggregateRoot
{
    private readonly List<UserRole> _roles = [];
    private readonly List<RefreshToken> _refreshTokens = [];
    private readonly List<UserToken> _userTokens = [];

    private User(Guid id, Email email, string firstName, string lastName, string passwordHash)
        : base(id)
    {
        Email = email;
        FirstName = firstName;
        LastName = lastName;
        PasswordHash = passwordHash;
        IsEmailConfirmed = false;
        IsActive = true;
    }

    private User()
        : base(Guid.Empty)
    {
        Email = null!;
        FirstName = null!;
        LastName = null!;
        PasswordHash = null!;
    }

    public Email Email { get; private set; }

    public string FirstName { get; private set; }

    public string LastName { get; private set; }

    public string PasswordHash { get; private set; }

    public bool IsEmailConfirmed { get; private set; }

    public bool IsActive { get; private set; }

    public string FullName => $"{FirstName} {LastName}";

    public IReadOnlyCollection<UserRole> Roles => _roles.AsReadOnly();

    public IReadOnlyCollection<RefreshToken> RefreshTokens => _refreshTokens.AsReadOnly();

    public IReadOnlyCollection<UserToken> UserTokens => _userTokens.AsReadOnly();

    public static User Register(
        Email email,
        string firstName,
        string lastName,
        string passwordHash,
        DateTime utcNow,
        Guid? createdBy = null)
    {
        Guard.NotNull(email, nameof(email));
        var normalizedFirstName = Guard.NotNullOrWhiteSpace(firstName, nameof(firstName)).Trim();
        var normalizedLastName = Guard.NotNullOrWhiteSpace(lastName, nameof(lastName)).Trim();
        var normalizedHash = Guard.NotNullOrWhiteSpace(passwordHash, nameof(passwordHash));

        var user = new User(Guid.NewGuid(), email, normalizedFirstName, normalizedLastName, normalizedHash);
        user.MarkCreated(utcNow, createdBy);
        user.RaiseDomainEvent(new UserRegisteredDomainEvent(user.Id, email.Value, utcNow));

        return user;
    }

    public void AssignRole(Role role, DateTime utcNow, Guid? updatedBy = null)
    {
        Guard.NotNull(role, nameof(role));

        if (_roles.Any(r => r.RoleId == role.Id))
        {
            throw new DomainException("The user already has this role.");
        }

        _roles.Add(new UserRole(Id, role.Id));
        MarkUpdated(utcNow, updatedBy);
        RaiseDomainEvent(new UserRoleAssignedDomainEvent(Id, role.Id, utcNow));
    }

    public void RemoveRole(Role role, DateTime utcNow, Guid? updatedBy = null)
    {
        Guard.NotNull(role, nameof(role));

        var existing = _roles.SingleOrDefault(r => r.RoleId == role.Id)
            ?? throw new DomainException("The user does not have this role.");

        _roles.Remove(existing);
        MarkUpdated(utcNow, updatedBy);
    }

    public void ConfirmEmail(DateTime utcNow, Guid? updatedBy = null)
    {
        if (IsEmailConfirmed)
        {
            throw new DomainException("The email is already confirmed.");
        }

        IsEmailConfirmed = true;
        MarkUpdated(utcNow, updatedBy);
    }

    public void ChangePassword(string newPasswordHash, DateTime utcNow, Guid? updatedBy = null)
    {
        PasswordHash = Guard.NotNullOrWhiteSpace(newPasswordHash, nameof(newPasswordHash));
        MarkUpdated(utcNow, updatedBy);
    }

    /// <summary>
    /// Mints a one-time, purpose-scoped token (email confirmation or password reset). To keep the
    /// invariant "at most one live token per purpose", any still-redeemable token of the same type is
    /// consumed first — so requesting a fresh reset link silently invalidates the previous one. The
    /// caller supplies the SHA-256 hash (the raw value is generated by Infrastructure) and the expiry.
    /// </summary>
    public UserToken IssueToken(
        string tokenHash,
        UserTokenType type,
        DateTime expiresAtUtc,
        DateTime utcNow)
    {
        foreach (var live in _userTokens.Where(t => t.Type == type && t.IsRedeemable(utcNow)))
        {
            live.Consume(utcNow);
        }

        var token = new UserToken(Id, tokenHash, type, expiresAtUtc, utcNow);
        _userTokens.Add(token);
        MarkUpdated(utcNow);

        return token;
    }

    /// <summary>
    /// Redeems an email-confirmation token: verifies the hash matches a redeemable token OF THE RIGHT
    /// TYPE, consumes it (single use), and flips <see cref="IsEmailConfirmed"/>. Returns false on any
    /// failure (unknown/expired/consumed/wrong-type/already-confirmed) so the handler can respond with
    /// one generic error — never revealing WHICH check failed.
    /// </summary>
    public bool ConfirmEmailWithToken(string presentedTokenHash, DateTime utcNow)
    {
        if (IsEmailConfirmed)
        {
            return false;
        }

        var token = _userTokens.SingleOrDefault(t =>
            t.Type == UserTokenType.EmailConfirmation
            && t.TokenHash == presentedTokenHash
            && t.IsRedeemable(utcNow));

        if (token is null)
        {
            return false;
        }

        token.Consume(utcNow);
        IsEmailConfirmed = true;
        MarkUpdated(utcNow);
        RaiseDomainEvent(new UserEmailConfirmedDomainEvent(Id, Email.Value, utcNow));

        return true;
    }

    /// <summary>
    /// Redeems a password-reset token: verifies the hash matches a redeemable reset token, consumes it,
    /// and sets the new password hash. Also revokes every active refresh token (a credential change must
    /// invalidate all existing sessions) and raises <see cref="UserPasswordResetDomainEvent"/>. Returns
    /// false on any failure so the handler responds with a single generic error.
    /// </summary>
    public bool ResetPasswordWithToken(string presentedTokenHash, string newPasswordHash, DateTime utcNow)
    {
        var token = _userTokens.SingleOrDefault(t =>
            t.Type == UserTokenType.PasswordReset
            && t.TokenHash == presentedTokenHash
            && t.IsRedeemable(utcNow));

        if (token is null)
        {
            return false;
        }

        token.Consume(utcNow);
        PasswordHash = Guard.NotNullOrWhiteSpace(newPasswordHash, nameof(newPasswordHash));
        RevokeAllRefreshTokens(utcNow);
        MarkUpdated(utcNow);
        RaiseDomainEvent(new UserPasswordResetDomainEvent(Id, Email.Value, utcNow));

        return true;
    }

    public void Deactivate(DateTime utcNow, Guid? updatedBy = null)
    {
        if (!IsActive)
        {
            throw new DomainException("The user is already inactive.");
        }

        IsActive = false;
        MarkUpdated(utcNow, updatedBy);
    }

    /// <summary>
    /// Issues a new refresh-token grant for this user. The caller passes the SHA-256 hash of the raw
    /// token (the raw value is generated and returned by Infrastructure and never enters the Domain).
    /// Login calls this after verifying credentials.
    /// </summary>
    public RefreshToken IssueRefreshToken(string tokenHash, DateTime expiresAtUtc, DateTime utcNow)
    {
        if (!IsActive)
        {
            throw new DomainException("Cannot issue a refresh token for an inactive user.");
        }

        var token = new RefreshToken(Id, tokenHash, expiresAtUtc, utcNow);
        _refreshTokens.Add(token);
        MarkUpdated(utcNow);

        return token;
    }

    /// <summary>
    /// Refresh-token ROTATION: validates the presented token by its hash, revokes it, and issues a
    /// fresh one — linking old→new so a replay of the already-consumed token is detectable. This is
    /// the whole point of DB-backed refresh tokens: it makes stolen-token reuse observable.
    /// </summary>
    public RefreshToken RotateRefreshToken(
        string presentedTokenHash,
        string newTokenHash,
        DateTime newExpiresAtUtc,
        DateTime utcNow)
    {
        var existing = _refreshTokens.SingleOrDefault(t => t.TokenHash == presentedTokenHash)
            ?? throw new DomainException("The refresh token was not found.");

        // Reuse detection: presenting a token that is already revoked (but was rotated) means the
        // token chain has been compromised. Defensively revoke every active token for this user.
        if (!existing.IsActive(utcNow))
        {
            RevokeAllRefreshTokens(utcNow);
            throw new DomainException("The refresh token is no longer active.");
        }

        var replacement = new RefreshToken(Id, newTokenHash, newExpiresAtUtc, utcNow);
        existing.Revoke(utcNow, replacement.TokenHash);
        _refreshTokens.Add(replacement);
        MarkUpdated(utcNow);

        return replacement;
    }

    /// <summary>
    /// Explicit single-session logout: revokes exactly the presented token. Silently no-ops if the
    /// token is unknown or already revoked — logout must be idempotent and must not leak whether a
    /// given token existed.
    /// </summary>
    public void RevokeRefreshToken(string presentedTokenHash, DateTime utcNow)
    {
        var existing = _refreshTokens.SingleOrDefault(t => t.TokenHash == presentedTokenHash);

        if (existing is null || !existing.IsActive(utcNow))
        {
            return;
        }

        existing.Revoke(utcNow);
        MarkUpdated(utcNow);
    }

    /// <summary>
    /// Revokes every currently-active grant — "log out everywhere". Also used defensively when a
    /// rotation reuse attack is detected.
    /// </summary>
    public void RevokeAllRefreshTokens(DateTime utcNow)
    {
        foreach (var token in _refreshTokens.Where(t => t.IsActive(utcNow)))
        {
            token.Revoke(utcNow);
        }

        MarkUpdated(utcNow);
    }
}
